services:
  task_broker:
    image: redis:8.4-alpine
    container_name: videomate_task_broker
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - task_broker_data:/data
    networks:
      - backend_network
    command: redis-server --requirepass ${REDIS_PASSWORD}

  database:
    image: mongo:8.2-noble
    container_name: videomate_database
    env_file:
      - .db.env
    ports:
      - "27017:27017"
    networks:
      - backend_network
    volumes:
      - database_data:/data/db

  backend:
    build: .
    command: ["npm", "run", "start"]
    container_name: videomate_backend
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/data:rw
      - app_uploads:/app/uploads:rw
    depends_on:
      - task_broker
      - database
    networks:
      - backend_network

  video_worker:
    build: .
    command: ["npm", "run", "worker:video"]
    container_name: videomate_video_worker
    env_file:
      - .env.prod
    volumes:
      - app_data:/app/data:rw
      - app_uploads:/app/uploads:rw
    depends_on:
      - task_broker
      - database
    networks:
      - backend_network

  frontend:
    build:
      context: ../frontend
      secrets:
        - env_file
    container_name: videomate_frontend
    volumes:
      - ../frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_data:/app/data:rw
      - app_uploads:/app/uploads:rw
    ports:
      - "5173:80"
    networks:
      - backend_network
    depends_on:
      - backend


secrets:
  env_file:
    file: ../frontend/.env

networks:
  backend_network:

volumes:
  database_data:
  task_broker_data:
  app_data:
  app_uploads: